# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/bhushCode/ML-Bootcamp/blob/master/Week-1/Day-1/day1.ipynb
"""

print("Welcome to the bootcamp")

print("i am developer")

lst=[1,2,3,4,5,6,7,8,9]

# Commented out IPython magic to ensure Python compatibility.
# %timeit

# Commented out IPython magic to ensure Python compatibility.
# %timeit [i**2 for i in lst]

import numpy as np
arr=np.array(lst)
arr

# Commented out IPython magic to ensure Python compatibility.
# %timeit arr ** 2

arr1 = np.random.radint(10,100,size = (5,6))

arr1 = np.random.randint(10,100,size = (5,6))

arr1 = np.random.radint(10,100,size = (5,6))
arr1

arr1 = np.random.randint(10,100,size = (5,6))
arr1

import pandas as pd

df = pd.DataFrame(data = arr1)
#print data
df

