# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/rosablazee/ML-Bootcamp/blob/master/Week-1/Day-1/day1.ipynb
"""

print("Welcome to the bootcamp")

print("hello")

# Commented out IPython magic to ensure Python compatibility.
list = [1,2,3,4,5,6,7,8,9]
# %timeit [i ** 2 for i in list]

!pip install numpy

import numpy as np

# Commented out IPython magic to ensure Python compatibility.
arr = np.array(list)
arr
# %timeit arr ** 2

arr1 = np.random.randint(10,100, size=(5,6))
arr1

!pip install pandas

import pandas as pd
df =pd.DataFrame(data=arr1)
df